name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: image build
        run: docker build . -t gcc-image

      - name: test
        run: docker run -v $(pwd):/home -w /home --rm gcc-image make test
